routes/web.php
<?php

use App\Http\Controllers\Appcontroller;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'Appcontroller@myfun');

Route::get('/', function () {
    return view("welcome");
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function() {
    // Route::get('/stories', 'StoriesController@index');
    // // Route::get('/stories/{id}', 'StoriesController@show');
    // Route::get('/stories/{story}', 'StoriesController@show'); // Route model binding Variable name need to match

    Route::resource('/stories', 'StoriesController');
});

app/Story.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
    protected $fillable = [
        'title', 'body', 'type', 'status'
    ];

    public function user() {
        return $this->belongsTo('app\User');
    }

}

app/Http/Controllers/StoriesController.php
<?php

namespace App\Http\Controllers;

use App\Story;
use Illuminate\Http\Request;

class StoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $stories = Story::where('user_id', auth()->user()->id )
        //     ->orderBy('id', 'DESC')
        //     ->get(); // Query here

        // Pagenate
        $stories = Story::where('user_id', auth()->user()->id )
            ->orderBy('id', 'DESC')
            ->paginate(2); // Query here

        return view('stories.index', [ // How to pass value
            'stories' => $stories,
            'name' => 'MyNamehere'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    // public function show( $id ) {
    //     // $story = Story::find( $id );
    //     $story = Story::findOrFail( $id );
    //     dd($story);
    // }

    public function show( Story $story ) {  // Route model binding Do Same as before
        return view( 'stories.show', ['story' => $story]); // Controller_Name.Method_Name
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function edit(Story $story)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Story $story)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function destroy(Story $story)
    {
        //
    }
}

resources/views/stories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> Add Story
                </div>

                <div class="card-body">
                    <form action="{{ route('stories.store') }}" method="post">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control">
                        </div>

                        <button class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/stories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Stories</div>

                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <td>Title</td>
                                <td>Type</td>
                                <td>Status</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($stories as $story)
                                <tr>
                                    <td>{{$story->title}}</td>
                                    <td>{{$story->type}}</td>
                                    <td>{{$story->status == 1 ? 'Yes' : 'No'}}</td>
                                    <td><a href="stories/{{ $story->id }}">View</a> </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $stories->links() }}  <!-- Pagination -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/stories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> {{ $story->title }} 
                    <a href="/stories" class="float-right">Back</a>
                </div>

                <div class="card-body">
                    {{ $story->body }}
                   
                    <p class="font-weight-bold">
                        Status: {{ $story->status == 1 ? 'Yes' : 'No' }}, 
                        Type: {{ $story->type }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection